name: Build & Test

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
      
      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build ./challenge/challenge.csproj --no-restore --configuration Release

      - name: Build Test
        run: dotnet build ./challenge.Tests/challenge.Tests.csproj --no-restore --configuration Release

      - name: Run Test
        run: dotnet test ./challenge.Tests/challenge.Tests.csproj
